import type { Report } from '../../../core/src/types/report.js';
import type { Severity } from '../../../core/src/types/finding.js';

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🔵',
  info: '⚪',
};

export function generateMarkdownReport(report: Report): string {
  const lines: string[] = [];

  lines.push(`# Last Mile 360 — Production Readiness Report`);
  lines.push('');
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| **Project** | ${report.projectName} |`);
  lines.push(`| **Date** | ${report.scanDate} |`);
  lines.push(`| **Score** | ${report.score} / 100 |`);
  lines.push(`| **Grade** | ${report.grade} |`);
  lines.push('');

  // Stack detection
  lines.push(`## Stack Detection`);
  lines.push('');
  lines.push(`| Component | Detected |`);
  lines.push(`|-----------|----------|`);
  lines.push(`| Language | ${report.codebase.language} |`);
  lines.push(`| Framework | ${report.codebase.framework ?? '—'} |`);
  lines.push(`| Database | ${report.codebase.database ?? '—'} |`);
  lines.push(`| Deploy Target | ${report.codebase.deployTarget ?? '—'} |`);
  lines.push(`| Package Manager | ${report.codebase.packageManager ?? '—'} |`);
  lines.push(`| Files Scanned | ${report.codebase.files.length} |`);
  lines.push('');

  // Summary
  lines.push(`## Summary`);
  lines.push('');
  lines.push(`| Severity | Count |`);
  lines.push(`|----------|-------|`);
  lines.push(`| 🔴 Critical | ${report.summary.critical} |`);
  lines.push(`| 🟠 High | ${report.summary.high} |`);
  lines.push(`| 🟡 Medium | ${report.summary.medium} |`);
  lines.push(`| 🔵 Low | ${report.summary.low} |`);
  lines.push(`| ⚪ Info | ${report.summary.info} |`);
  lines.push(`| **Total** | **${report.summary.total}** |`);
  lines.push('');

  // Category scores
  lines.push(`## Category Scores`);
  lines.push('');
  lines.push(`| Category | Score | Weight | Findings |`);
  lines.push(`|----------|-------|--------|----------|`);
  for (const [cat, data] of Object.entries(report.categoryScores)) {
    lines.push(`| ${cat} | ${data.score}/100 | ${(data.weight * 100).toFixed(0)}% | ${data.findings} |`);
  }
  lines.push('');

  // Findings by severity
  const severities: Severity[] = ['critical', 'high', 'medium', 'low', 'info'];
  for (const sev of severities) {
    const items = report.findings.filter((f) => f.severity === sev);
    if (items.length === 0) continue;

    lines.push(`## ${SEVERITY_EMOJI[sev]} ${sev.charAt(0).toUpperCase() + sev.slice(1)} Findings (${items.length})`);
    lines.push('');

    for (const f of items) {
      lines.push(`### \`${f.ruleId}\` — ${f.message}`);
      lines.push('');
      lines.push(`- **File:** \`${f.file}:${f.line}\``);
      if (f.cwe) lines.push(`- **CWE:** ${f.cwe}`);
      if (f.fix) {
        lines.push(`- **Fix:** ${f.fix}`);
      }
      lines.push('');
    }
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by [Last Mile 360](https://github.com/itallstartedwithaidea/last-mile) v0.0.1*`);
  lines.push('');

  return lines.join('\n');
}
